server:
  servlet:
    context-path: /shop

mybatis:
  type-aliases-package: com.cssl.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///shop?serverTimezone=GMT
    username: root
    password: 123

  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8

#templates start
  thymeleaf:
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    servlet:
      content-type: text/html
#templates end

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
